server.port=8081

spring.datasource.url=jdbc:postgresql://db:5432/weatherdb
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

weather.api.key=${RAPIDAPI_KEY}
weather.api.host=${RAPIDAPI_HOST}

management.endpoints.web.exposure.include=health,prometheus,info